# Generated by Django 4.1.5 on 2023-01-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(default='images/fatcat.png', upload_to='images/'),
            preserve_default=False,
        ),
    ]
