# Generated by Django 4.1.5 on 2023-01-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='usersWhoLike',
            field=models.ManyToManyField(related_name='likedPosts', to='users.user'),
        ),
    ]
