# Generated by Django 4.1.5 on 2023-01-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
