# Generated by Django 4.1.5 on 2023-01-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_comment_post_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='usersWhoLike',
            field=models.ManyToManyField(null=True, related_name='likedPosts', to='users.user'),
        ),
    ]
