# Generated by Django 4.1.5 on 2023-01-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_post_userswholike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aboutMe',
            field=models.TextField(default='Not Set'),
            preserve_default=False,
        ),
    ]
